package com.loan.constants;

public enum ApplicationStatus {
    ELIGIBLE,
    NOT_ELIGIBLE,
    DOCUMENT_UPLOAD_PENDING,
    DOCUMENT_VERIFICATION_PENDING,
    DOCUMENT_RETURNED_FOR_CORRECTION,
    DOCUMENT_REJECTED,
    DOCUMENT_APPROVED,
    LOAN_APPROVED,
    LOAN_REJECTED,
    SANCTION_LETTER_SENT,
    SANCTION_LETTER_ACCEPTED,
    SANCTION_LETTER_REJECTED,
    LOAN_DISBURSED
}
