package com.loan.constants;

public enum EmailTemplateName {
	
	LOAN_SANCTION,
    LOAN_REJECTED,
    RESET_PASSWORD,
    LOAN_APPLICATION_SUBMITTED,
    DOCUMENT_REMINDER,
    LOAN_DISBURSED,
    SANCTION_LETTER_ACCEPTED,
    SANCTION_LETTER_REJECTED,
    DOCUMENT_RETURNED
}
