export type ApplicationInitStatus =
  | 'USER_CREATED'
  | 'APPLIED'
  | 'DOCUMENT_VERIFICATION_PENDING'
  | 'DOCUMENT_RETURNED'
  | 'DOCUMENT_APPROVED'
  | 'DOCUMENT_REJECTED'
  | 'LOAN_APPROVED'
  | 'SANCTION_ACCEPTED'
  | 'LOAN_DISBURSED'
  | 'LOAN_CLOSED';
